/**
 * Phase 2 — admin/owner-only preview panel for region-restricted
 * contributions.
 *
 * Renders the cached "before" PNG (combined map cropped to the region) and
 * the "after" PNG (combined merged with the upload, with green = newly
 * added chunks, orange = overwritten chunks) side by side. Both previews
 * are wrapped in a {@link MapViewer} so reviewers get the same pan/zoom,
 * coordinate readout, and landmark overlay they have on the TOPS map
 * viewer — restricted to the selected region only (the backend never
 * renders anything outside the requested bounds).
 *
 * Both blobs are fetched on mount; the component degrades to an error
 * message if the backend returns 404 (feature flag off, no region
 * recorded, or PNG not yet generated by the approve preview pass).
 */

import { useMemo, useState } from "react";
import {
  getRegionPreviewImage,
  type ContributionRegion,
  type ContributionRegionTuple,
  normalizeContributionRegion,
} from "@/lib/api";
import { useTranslation } from "@/lib/i18n";
import { Loader2 } from "lucide-react";
import { useEffectWithAbort } from "@/hooks/useEffectWithAbort";
import { MapViewer, type MapStats, type WorldPointMarker } from "./MapViewer";
import { useLandmarksOverlay } from "@/hooks/useOverlayData";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";

const TILE_SIZE = 32;

interface Props {
  contributionId: string;
  /** Phase C — admin-only padding so reviewers can see context
   *  around the rectangle. Backend caps the value and falls back to 0
   *  for non-admin callers. */
  paddingChunks?: number;
  /** Bump to force a reload (e.g. after the admin saves new bounds and
   *  the server invalidated cached previews). */
  refreshKey?: number;
  /** Region currently displayed (in world blocks, inclusive). Used to
   *  build the synthetic {@link MapStats} that powers the coordinate
   *  overlay and to filter landmarks down to the visible area. Accepts
   *  both the object and 4-tuple wire forms. */
  region?: ContributionRegion | ContributionRegionTuple | null;
}

interface LoadedImage {
  url: string;
  naturalWidth: number;
  naturalHeight: number;
}

/** Load a Blob into an HTMLImageElement so we can read its natural size
 *  (needed to build the synthetic MapStats). The returned promise resolves
 *  with both the object URL and the natural dimensions. */
async function loadBlobAsImage(blob: Blob): Promise<LoadedImage> {
  const url = URL.createObjectURL(blob);
  try {
    const img = await new Promise<HTMLImageElement>((resolve, reject) => {
      const el = new Image();
      el.onload = () => resolve(el);
      el.onerror = () => reject(new Error("preview image failed to decode"));
      el.src = url;
    });
    return { url, naturalWidth: img.naturalWidth, naturalHeight: img.naturalHeight };
  } catch (err) {
    URL.revokeObjectURL(url);
    throw err;
  }
}

export function ContributionBeforeAfter({
  contributionId,
  paddingChunks = 0,
  refreshKey = 0,
  region = null,
}: Props) {
  const { t } = useTranslation();
  const [before, setBefore] = useState<LoadedImage | null>(null);
  const [after, setAfter] = useState<LoadedImage | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showLandmarks, setShowLandmarks] = useState(false);

  // Landmark overlay is opt-in to avoid fetching the (potentially large)
  // landmarks file just for a quick before/after glance.
  const landmarksQuery = useLandmarksOverlay();
  const allLandmarks = landmarksQuery.data?.data;

  const normalisedRegion = useMemo(() => normalizeContributionRegion(region), [region]);

  // Padded extent in world blocks — must match the backend's
  // ``_render_region_before_after`` (region + paddingChunks * TILE_SIZE
  // on each edge, inclusive both ends).
  const paddedExtent = useMemo(() => {
    if (!normalisedRegion) return null;
    const pad = paddingChunks * TILE_SIZE;
    const minX = normalisedRegion.min_x - pad;
    const maxX = normalisedRegion.max_x + pad;
    const minZ = normalisedRegion.min_z - pad;
    const maxZ = normalisedRegion.max_z + pad;
    return {
      minX,
      maxX,
      minZ,
      maxZ,
      widthBlocks: maxX - minX + 1,
      heightBlocks: maxZ - minZ + 1,
      centerX: Math.floor((minX + maxX) / 2),
      centerZ: Math.floor((minZ + maxZ) / 2),
    };
  }, [normalisedRegion, paddingChunks]);

  // Synthetic MapStats so MapViewer's coordinate overlay reports world
  // coordinates for the cropped preview. ``width_blocks`` / ``height_blocks``
  // must reflect the *world* area covered by the PNG, not its pixel size
  // — the viewer derives pixel-to-block scaling from the image's natural
  // dimensions.
  const stats = useMemo<MapStats | null>(() => {
    if (!paddedExtent || !before) return null;
    return {
      pieces: 0,
      size_mb: 0,
      width_chunks: Math.round(paddedExtent.widthBlocks / TILE_SIZE),
      height_chunks: Math.round(paddedExtent.heightBlocks / TILE_SIZE),
      width_blocks: paddedExtent.widthBlocks,
      height_blocks: paddedExtent.heightBlocks,
      start_x: paddedExtent.minX,
      start_z: paddedExtent.minZ,
    };
  }, [paddedExtent, before]);

  // Filter landmarks down to the rendered area so we don't draw markers
  // that fall outside the cropped image. Disabled when the user hasn't
  // opted in.
  const landmarkPoints = useMemo<WorldPointMarker[]>(() => {
    if (!showLandmarks || !allLandmarks || !paddedExtent) return [];
    return allLandmarks.filter(
      (p) =>
        p.x >= paddedExtent.minX &&
        p.x <= paddedExtent.maxX &&
        p.z >= paddedExtent.minZ &&
        p.z <= paddedExtent.maxZ,
    );
  }, [showLandmarks, allLandmarks, paddedExtent]);

  // Stable focus reference so MapViewer only flies once per region change.
  const focusPoint = useMemo(
    () => (paddedExtent ? { x: paddedExtent.centerX, z: paddedExtent.centerZ } : undefined),
    [paddedExtent],
  );

  // The "center" toolbar button should return reviewers to the selected
  // region's center rather than the world origin (0, 0). Uses the
  // unpadded region bounds so the target matches what was contributed.
  const regionCenter = useMemo(
    () =>
      normalisedRegion
        ? {
            x: Math.floor((normalisedRegion.min_x + normalisedRegion.max_x) / 2),
            z: Math.floor((normalisedRegion.min_z + normalisedRegion.max_z) / 2),
          }
        : null,
    [normalisedRegion],
  );

  useEffectWithAbort(
    ({ signal }) => {
      let createdBefore: LoadedImage | null = null;
      let createdAfter: LoadedImage | null = null;
      setLoading(true);
      setError(null);
      setBefore(null);
      setAfter(null);
      (async () => {
        try {
          const [bBlob, aBlob] = await Promise.all([
            getRegionPreviewImage(contributionId, "before", paddingChunks),
            getRegionPreviewImage(contributionId, "after", paddingChunks),
          ]);
          if (signal.aborted) return;
          const [b, a] = await Promise.all([loadBlobAsImage(bBlob), loadBlobAsImage(aBlob)]);
          if (signal.aborted) {
            URL.revokeObjectURL(b.url);
            URL.revokeObjectURL(a.url);
            return;
          }
          createdBefore = b;
          createdAfter = a;
          setBefore(b);
          setAfter(a);
        } catch (e) {
          if (!signal.aborted) {
            setError(e instanceof Error ? e.message : String(e));
          }
        } finally {
          if (!signal.aborted) setLoading(false);
        }
      })();
      return () => {
        if (createdBefore) URL.revokeObjectURL(createdBefore.url);
        if (createdAfter) URL.revokeObjectURL(createdAfter.url);
      };
    },
    [contributionId, paddingChunks, refreshKey],
  );

  if (loading) {
    return (
      <div className="flex items-center gap-2 text-sm text-muted-foreground">
        <Loader2 className="h-4 w-4 animate-spin" /> {t("contributePage.beforeAfter.loading")}
      </div>
    );
  }
  if (error) {
    return (
      <div className="text-sm text-destructive">
        {t("contributePage.beforeAfter.unavailable", { error })}
      </div>
    );
  }
  if (!before || !after) return null;

  return (
    <div className="space-y-2">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div className="text-xs text-muted-foreground">{t("contributePage.beforeAfter.help")}</div>
        <Label className="flex items-center gap-2 text-xs">
          <Switch
            checked={showLandmarks}
            onCheckedChange={setShowLandmarks}
            aria-label={t("contributePage.beforeAfter.toggleLandmarks")}
          />
          {t("contributePage.beforeAfter.landmarks")}
        </Label>
      </div>
      <div className="grid grid-cols-1 gap-2 md:grid-cols-2">
        <figure className="space-y-1">
          <figcaption className="text-xs font-medium">
            {t("contributePage.beforeAfter.before")}
          </figcaption>
          <MapViewer
            imageUrl={before.url}
            stats={stats}
            alt={t("contributePage.beforeAfter.beforeAlt")}
            height="360px"
            focusPoint={focusPoint}
            focusZoom={2}
            overlayPoints={landmarkPoints}
            centerTarget={regionCenter}
          />
        </figure>
        <figure className="space-y-1">
          <figcaption className="text-xs font-medium">
            {t("contributePage.beforeAfter.after")}
          </figcaption>
          <MapViewer
            imageUrl={after.url}
            stats={stats}
            alt={t("contributePage.beforeAfter.afterAlt")}
            height="360px"
            focusPoint={focusPoint}
            focusZoom={2}
            overlayPoints={landmarkPoints}
            centerTarget={regionCenter}
          />
        </figure>
      </div>
    </div>
  );
}
