import type { ReactNode } from "react";
import { NavLink } from "react-router-dom";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Upload,
  KeyRound,
  Eye,
  Check,
  Clock,
  ShieldCheck,
  AlertTriangle,
  Map as MapIcon,
  HelpCircle,
} from "lucide-react";
import contributionExampleImg from "@/assets/ContributionExample.png";

export function ContributingToTopsMapPost() {
  return (
    <div className="space-y-6 text-sm leading-relaxed">
      <Lede>
        The TOPS map you see at{" "}
        <NavLink
          to="/multiplayer/tops-map"
          className="underline decoration-dotted underline-offset-2 hover:text-primary"
        >
          /multiplayer/tops-map
        </NavLink>{" "}
        isn&rsquo;t generated by a server crawler &mdash; it&rsquo;s stitched together from{" "}
        <strong>real player explorations</strong>. Every tile you see was once part of
        someone&rsquo;s local <Code>.db</Code> map cache. This guide walks through how to add your
        slice of the world to the shared map, what happens behind the scenes, and how to avoid the
        pitfalls that get contributions rejected.
      </Lede>

      <Section title="The 30-second version" icon={<MapIcon className="size-4" />}>
        <Ol>
          {/* <li>
            Get a <strong>Read &amp; Contribute</strong> API key (or upgrade
            yours).
          </li> */}
          <li>
            Find your map cache <Code>.db</Code> file from your <em>Vintage Story</em> data folder.
          </li>
          <li>
            Open the{" "}
            <NavLink
              to="/multiplayer/contribute"
              className="underline decoration-dotted underline-offset-2 hover:text-primary"
            >
              Contribute page
            </NavLink>
            , drop the file in, optionally add your name, and submit.
          </li>
          <li>
            Wait for an admin to approve. Your chunks get merged into the shared map and rendered
            into the public tile layer.
          </li>
        </Ol>
        <Callout tone="info">
          By default, contributions only <strong>fill gaps</strong> &mdash; they never overwrite
          chunks that already exist. That makes contributing safe: you cannot accidentally damage
          someone else&rsquo;s work.
        </Callout>
      </Section>

      <Section title="Step 1 — Get a contributor API key" icon={<KeyRound className="size-4" />}>
        <P>
          Cairn uses tiered API keys. To upload, your key needs the{" "}
          <strong>Read &amp; Contribute</strong> tier (or higher). Read-only keys can browse the
          TOPS map but the contribute form will be hidden behind an &ldquo;access required&rdquo;
          notice.
        </P>
        <P>
          If a friend or admin sent you an invite link, claiming it gives you a key automatically.
          Otherwise ask in the community to be invited &mdash; contributor access is intentionally
          gated to keep the map trustworthy.
        </P>
      </Section>

      <Section title="Step 2 — Find your map cache file" icon={<HelpCircle className="size-4" />}>
        <P>
          Vintage Story stores your explored map data in a small SQLite database, separate from your
          save file. On Windows it lives roughly here:
        </P>
        <Pre>{`%APPDATA%\\VintagestoryData\\Maps\\<server-id>\\map.db`}</Pre>
        <P>
          Each multiplayer server you&rsquo;ve joined has its own folder. If you have several and
          aren&rsquo;t sure which is which, the{" "}
          <NavLink
            to="/multiplayer/identify"
            className="underline decoration-dotted underline-offset-2 hover:text-primary"
          >
            Identify Maps
          </NavLink>{" "}
          tool can match them up using your client log.
        </P>
        <Callout tone="warning">
          Upload the <Code>.db</Code> map cache &mdash; <em>not</em> a <Code>.vcdbs</Code> save
          file. Save files are for the singleplayer tools and will be rejected by the validator.
        </Callout>
      </Section>

      <Section title="Step 3 — Submit your contribution" icon={<Upload className="size-4" />}>
        <P>The Contribute page asks for three things:</P>
        <Ul>
          <li>
            <strong>The file</strong> &mdash; drag and drop, or click to browse. Uploads go directly
            to object storage with a progress bar; nothing is stored on the app server itself.
          </li>
          <li>
            <strong>Your name (optional)</strong> &mdash; shown next to your contribution in the
            public history. Leave it blank to appear as
            <em> Anonymous</em>. You can also opt in/out globally from your{" "}
            <NavLink
              to="/account"
              className="underline decoration-dotted underline-offset-2 hover:text-primary"
            >
              Account page
            </NavLink>
            .
          </li>
          <li>
            <strong>Region (advanced, optional)</strong> &mdash; if you have the{" "}
            <Badge variant="secondary">region_overwrite</Badge> permission, you can draw a rectangle
            to <em>replace</em> chunks inside it instead of just gap-filling. This is for fixing
            stale or wrong chunks, and it&rsquo;s gated for a reason &mdash; see below.
          </li>
        </Ul>
      </Section>

      <Section title="What happens after you click Submit" icon={<Eye className="size-4" />}>
        <Ol>
          <li>
            Your file uploads directly to R2 storage via a one-time presigned URL. The app then
            registers it as <em>pending</em>.
          </li>
          <li>
            A preview PNG is rendered so admins can eyeball it. A <strong>match score</strong> is
            computed in the background by sampling chunks against the existing TOPS map.
          </li>
          <li>
            The contribution shows up in the pending list with a badge:
            <span className="inline-flex flex-wrap gap-1.5 ml-2 align-middle">
              <Badge className="bg-emerald-600 hover:bg-emerald-600">Looks like our map</Badge>
              <Badge variant="secondary">Partial match</Badge>
              <Badge variant="destructive">May be wrong file</Badge>
            </span>
          </li>
          <li>
            An admin reviews the preview and approves or rejects. On approval, the chunks are merged
            under a database lock and the affected portion of the public TOPS image is regenerated.
          </li>
        </Ol>
        <P>
          You can <strong>withdraw</strong> a pending contribution any time before it&rsquo;s
          approved (limited to 3 withdrawals per ISO week to discourage churn).
        </P>
        <figure className="space-y-2">
          <a
            href={contributionExampleImg}
            target="_blank"
            rel="noreferrer"
            className="block overflow-hidden rounded border bg-muted/40"
          >
            <img
              src={contributionExampleImg}
              alt="Pending Contributions card showing two contributions with their match-score badges and a preview open for one of them."
              loading="lazy"
              className="w-full h-auto"
            />
          </a>
          <figcaption className="text-xs text-muted-foreground text-center">
            Example: the Pending Contributions card after a successful upload &mdash; two
            contributions with their match-score badges, and a preview open for one of them.
          </figcaption>
        </figure>
      </Section>

      <Section title="Gap-fill vs Region Overwrite" icon={<ShieldCheck className="size-4" />}>
        <div className="grid gap-3 sm:grid-cols-2">
          <MiniCard heading="Gap-fill (default)" badge={<Badge variant="secondary">safe</Badge>}>
            Only adds chunks that don&rsquo;t exist yet. Existing chunks are untouched. This is the
            right choice 95% of the time.
          </MiniCard>
          <MiniCard heading="Region overwrite" badge={<Badge>permission required</Badge>}>
            Replaces every tile inside the rectangle you drew with the ones from your file. Use this
            to fix outdated or vandalised areas.
          </MiniCard>
        </div>
        <Callout tone="info">
          For privacy, the exact bounds of region-overwrite contributions are only visible to you
          and admins &mdash; other viewers see the contribution but not the rectangle.
        </Callout>
      </Section>

      <Section title="Cooldowns and limits" icon={<Clock className="size-4" />}>
        <Ul>
          <li>
            <strong>One pending contribution at a time</strong> per contributor. Wait for review (or
            withdraw) before submitting another.
          </li>
          <li>
            <strong>One approved contribution per 7 days</strong>. This prevents flooding the queue
            and keeps the public history readable.
          </li>
          <li>
            <strong>3 withdrawals per ISO week</strong>. If you hit the cap, the form will tell you
            and disable Submit until the window resets.
          </li>
        </Ul>
        <P>
          When a cooldown is active, the Contribute page shows the exact reason (
          <Code>cooldown_reason</Code>) so you know what to wait for.
        </P>
      </Section>

      <Section
        title="Why a contribution might be rejected"
        icon={<AlertTriangle className="size-4" />}
      >
        <Ul>
          <li>
            <strong>Wrong file type.</strong> Only valid SQLite map caches with a non-empty{" "}
            <Code>mappiece</Code> table pass validation.
          </li>
          <li>
            <strong>Doesn&rsquo;t match this map.</strong> If the match-score badge says{" "}
            <em>May be wrong file</em>, your file is probably from a different server. Use{" "}
            <NavLink
              to="/multiplayer/identify"
              className="underline decoration-dotted underline-offset-2 hover:text-primary"
            >
              Identify Maps
            </NavLink>{" "}
            to confirm.
          </li>
          <li>
            <strong>Empty / nothing new.</strong> If every tile you have is already on the shared
            map, there&rsquo;s nothing to merge.
          </li>
          <li>
            <strong>Region misuse.</strong> Region-overwrite over a busy area with no clear
            improvement is usually rejected.
          </li>
        </Ul>
      </Section>

      <Section title="After approval" icon={<Check className="size-4" />}>
        <P>
          Approved contributions appear in the public <strong>Recent Contributions</strong> list for
          14 days, with the contributor name (or <em>Anonymous</em>) and tile count. Admins retain a
          90-day window and can revert an individual contribution if a problem is spotted later,
          with a cascading conflict check against newer contributions on top of it.
        </P>
        <P>
          And that&rsquo;s it &mdash; your chunks are now part of the shared world. Thanks for
          contributing.
        </P>
      </Section>

      <Separator />

      <Card>
        <CardContent className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between p-4">
          <div className="text-sm">
            <p className="font-medium text-foreground">Ready to upload?</p>
            <p className="text-muted-foreground">
              Head to the Contribute page with your <Code>.db</Code> file in hand.
            </p>
          </div>
          <NavLink to="/multiplayer/contribute">
            <Button>
              <Upload className="size-4 mr-1.5" />
              Open Contribute
            </Button>
          </NavLink>
        </CardContent>
      </Card>
    </div>
  );
}

/* ---------- small presentational helpers (post-local) ---------- */

function Lede({ children }: { children: ReactNode }) {
  return (
    <p className="text-base text-foreground/90 leading-relaxed border-l-2 border-primary/40 pl-3">
      {children}
    </p>
  );
}

function Section({
  title,
  icon,
  children,
}: {
  title: string;
  icon?: ReactNode;
  children: ReactNode;
}) {
  return (
    <section className="space-y-3">
      <h2 className="flex items-center gap-2 text-base font-semibold text-foreground">
        {icon ? <span className="text-primary">{icon}</span> : null}
        {title}
      </h2>
      <div className="space-y-3 text-muted-foreground">{children}</div>
    </section>
  );
}

function P({ children }: { children: ReactNode }) {
  return <p>{children}</p>;
}

function Ul({ children }: { children: ReactNode }) {
  return <ul className="list-disc list-outside space-y-1.5 pl-5">{children}</ul>;
}

function Ol({ children }: { children: ReactNode }) {
  return <ol className="list-decimal list-outside space-y-1.5 pl-5">{children}</ol>;
}

function Code({ children }: { children: ReactNode }) {
  return (
    <code className="rounded bg-muted px-1 py-0.5 text-xs font-mono text-foreground">
      {children}
    </code>
  );
}

function Pre({ children }: { children: ReactNode }) {
  return (
    <pre className="overflow-x-auto rounded border bg-muted/40 p-3 text-xs font-mono text-foreground">
      {children}
    </pre>
  );
}

function Callout({ tone, children }: { tone: "info" | "warning"; children: ReactNode }) {
  const cls =
    tone === "warning"
      ? "border-amber-300 bg-amber-50 text-amber-900"
      : "border-sky-300 bg-sky-50 text-sky-900";
  return <div className={`rounded border ${cls} p-3 text-xs`}>{children}</div>;
}

function MiniCard({
  heading,
  badge,
  children,
}: {
  heading: string;
  badge?: ReactNode;
  children: ReactNode;
}) {
  return (
    <div className="rounded border bg-card p-3 space-y-1.5">
      <div className="flex items-center justify-between gap-2">
        <p className="font-medium text-foreground text-sm">{heading}</p>
        {badge}
      </div>
      <p className="text-xs text-muted-foreground">{children}</p>
    </div>
  );
}
